### ISSUE TITLE
ModuleNotFoundError: No module named 'requests_jwt'

### ISSUE THREAD

**Issue by tbnorth** [shaarli/python-shaarli-client#35]
(update: setting requests-jwt == 0.4 in setup.py (git install) fixes this)

Ubuntu 18.04, followed [these instructions](https://python-shaarli-client.readthedocs.io/en/latest/user/installation.html#from-the-python-package-index-pypi).
```shell
shaarli --help
Traceback (most recent call last):
  File "/home/tbrown/.virtualenvs/shaarli/bin/shaarli", line 7, in <module>
    from shaarli_client.main import main
  File "/home/tbrown/.virtualenvs/shaarli/lib/python3.6/site-packages/shaarli_client/main.py", line 7, in <module>
    from .client import ShaarliV1Client
  File "/home/tbrown/.virtualenvs/shaarli/lib/python3.6/site-packages/shaarli_client/client/__init__.py", line 2, in <module>
    from .v1 import InvalidEndpointParameters, ShaarliV1Client
  File "/home/tbrown/.virtualenvs/shaarli/lib/python3.6/site-packages/shaarli_client/client/v1.py", line 7, in <module>
    from requests_jwt import JWTAuth
ModuleNotFoundError: No module named 'requests_jwt'

pip freeze
certifi==2018.10.15
chardet==3.0.4
idna==2.7
pkg-resources==0.0.0
PyJWT==1.6.4
requests==2.20.0
requests-jwt==0.5.1
shaarli-client==0.2.0
urllib3==1.24

(shaarli) tb:ot: /mnt/edata/edata/shaarli
shaarli:0> python
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from requests_jwt import JWTAuth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests_jwt'
```
Something upstream broken maybe?

**Comment by virtualtam** [comment]
Hi @tbnorth (and sorry for the late feedback)!

There have been breaking changes in the latest releases of `requests_jwt`, I'll submit a patch to pin the version to `0.4` while we decide whether we should upgrade it or find a better solution (the author has flagged the project as not being actively maintained).
